dataset_path: "data/noma/serialized/test.h5"
model_path: "deCIFer_model/ckpt.pt"
params_dict:
  q_pre_scale_uniform: [0.8, 0.9, 0.95, 0.975, 0.99, 1.0, 1.01, 1.025, 1.05, 1.1, 1.2]
  q_pre_scale_abc: [[1.0, 1.0, 0.8], [1.0, 1.0, 0.95], [1.0, 1.0, 0.975], [1.0, 1.0, 0.99], [1.0, 1.0, 1.0], [1.0, 1.0, 1.01], [1.0, 1.0, 1.025], [1.0, 1.0, 1.05], [1.0, 1.0, 1.1]]
  peak_asymmetry: [0.0, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0]
  particle_size: [1, 5, 10, 20, 25, 30, 35, 40, 45, 50, 75, 100]
default_params_dict:
  base_fwhm: 0.05
batch_size: 10
n_repeats: 10
max_new_tokens: 3076
add_composition: true
add_spacegroup: false
crystal_system: "trigonal"
target_elements: ["Fe", "O"]
element_match_mode: "exact"
seed: 102
use_multi_phase: false
combinatory: false
output: "ablation_mainfig_trigonal_large_FeO.pkl"
