dataset_path: "../../phd_projects/deCIFer/data/chili100k_clean/serialized/test.h5"
model_path: "../../phd_projects/deCIFer/experiments/model__conditioned_mlp_augmentation__context_3076__robust_full_trainingcurves/ckpt.pt"
params_dict:
  particle_size: [1, 5, 10, 20, 50, 100]
  #peak_asymmetry: [-1.0, -0.5, 0.0, 0.5, 1.0]
  #q_shift: [-0.5, -0.1, 0.0, 0.1, 0.5]
default_params_dict:
  base_fwhm: 0.05
batch_size: 1
n_repeats: 10
max_new_tokens: 1000 #3076
add_composition: true
add_spacegroup: false
use_multi_phase: false
combinatory: false
output: "particle_size_experimental_results_comp.pkl"
