dataset_path: "../deCIFer/data/crystallm/full_new/serialized/test.h5"
model_path: "../deCIFer/model__conditioned_mlp_augmentation__context_3076__robust/ckpt.pt"
params_dict:
  particle_size: [1, 5, 10, 20, 25, 30, 35, 40, 45, 50, 100]
  peak_asymmetry: [-1.0, -0.75, -0.5, -0.25, -0.1, 0.0, 0.1, 0.25, 0.5, 0.75, 1.0]
  q_shift: [-0.5, -0.25, -0.1, -0.05, -0.01, 0.0, 0.01, 0.05, 0.1, 0.25, 0.5]
  q_scale: [0.8, 0.9, 0.95, 0.975, 0.99, 1.0, 1.01, 1.025, 1.05, 1.1, 1.2]
  eta: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  noise: [0.0, 0.01, 0.02, 0.03, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.2]
  base_fwhm: [0.001, 0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.3, 0.4]
default_params_dict:
  base_fwhm: 0.075
batch_size: 10
n_repeats: 10
max_new_tokens: 3076
add_composition: true
add_spacegroup: false
crystal_system: "cubic"
seed: 102
use_multi_phase: false
combinatory: false
output: "ablation_results_cubic_crystal_params_comp_2.pkl"
