dataset_path: "../../phd_projects/deCIFer/data/chili100k_clean/serialized/test.h5"
model_path: "../../phd_projects/deCIFer/experiments/model__conditioned_mlp_augmentation__context_3076__robust_full_trainingcurves/ckpt.pt"
params_dict:
  #particle_size: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  #peak_asymmetry: [-0.2, -0.1, -0.05, -0.01, 0.0, 0.01, 0.05, 0.1, 0.2]
  #q_shift: [0.0, 0.1, 0.5] #[-0.5, -0.1, 0.0, 0.1, 0.5]
  #q_scale: [0.7, 0.8, 1.2, 1.3] #[0.9, 0.95, 0.99, 1.0, 1.01, 1.05, 1.1]
  mask_ranges: [[[8.0, 9.0]], [[7.0, 9.0]], [[6.0, 9.0]], [[5.0, 9.0]], [[2.0, 3.0]], [[2.0, 4.0]], [[2.0, 5.0]]]
  #preferred_orientation_range: [[0.9, 1.0], [0.5, 1.0], [0.1, 1.0]]
  #chebychev_norm_coeffs: [[-0.1, -0.2, 0.1], [-0.2, 0.0, 0.1], [-0.1, -0.2, 0.5], [0.1, 0.2, 0.3]]
  #phase_scales: [[0.0, 1.0], [1.0, 0.0], [0.5, 0.5], [0.1, 0.9], [0.9, 0.1]]
default_params_dict:
  #chebychev_order: 3
  base_fwhm: 0.05
batch_size: 1
n_repeats: 2
max_new_tokens: 2000 #3076
add_composition: true
add_spacegroup: false
crystal_system: "cubic"
seed: 104
output: "testing_experimental_results_comp.pkl"
