out_dir: 'testing_deeper_mlp'
eval_interval: 10  # how often to evaluate against the validation set
eval_iters_train: 10
eval_iters_val: 10
log_interval: 1  # how often to print to the console (1 = every iteration)
init_from: 'scratch'

device: 'cuda'
compile: False

dtype: 'float16'

# whether to always save a checkpoint
always_save_checkpoint: True

# whether to validate with a validation set
validate: True

dataset: 'data/crystallm/1k'
batch_size: 4
block_size: 1024

n_layer: 2
n_head: 2
n_embd: 512
dropout: 0.1

learning_rate: 1e-3
max_iters: 1000
lr_decay_iters: 1000
min_lr: 1e-4
beta2: 0.99

warmup_iters: 10

early_stopping_patience: 5

condition_with_mlp_emb: True
cond_hidden_size: 512
cond_num_hidden_layers: 1

condition_with_cl_emb: False
boundary_masking: True
